#! /bin/bash

echo Downloading the bootstrap installation. One moment please...
wget -q -O /tmp/install_salt.sh https://bootstrap.saltstack.com

echo ""
echo Please insert the Saltstack master IP adress.

read -p 'Saltstack Master IP: ' ip

ping -q -c5 $ip > /dev/null
 
if [ $? -ne 0 ]; then
	echo ""
	echo ERROR: Unable to ping IP adress!
	read -p 'Do you whish to continue with '$ip' (y/n): ' cont 

	if [ "$cont" == "y" ] || [ "$cont" == "Y" ] || [ "$cont" == "yes" ] || [ "$cont" == "Yes" ]; then
		echo ""
		echo Continuing with $ip
	elif [ "$cont" == "n" ] || [ "$cont" == "N" ] || [ "$cont" == "no" ] || [ "$cont" == "No" ]; then
		echo ""
		echo Exiting Saltstack Minion install!
		exit
	else
		echo ""
		echo No valid input detected!
		echo Exiting Saltstack Minion install!
		exit
	fi
else
	echo Saltstack Master found!
fi

echo ""
echo Installing Saltstack with Saltstack Master IP $ip
sudo sh /tmp/install_salt.sh -A $ip

echo ""
echo Saltstack Minion succesfully installed!
