#! /bin/bash

# Defining colors
ERROR='\033[0;31m'
INFO='\033[0;32m'
NC='\033[0m'

# Confirm installation
echo -e "${INFO}INFO${NC}: Installing prerequisites"
sudo apt-get update
sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.0 libgd2-xpm-dev

#Downloading and compiling the source
echo -e "${INFO}INFO${NC}: Downloading the source"
wget -q -O /tmp/nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.3.4.tar.gz
errorcode=$?
if [ $errorcode != 0 ]; then
	echo -e "${ERROR}ERROR${NC}: An error occured while trying to download the file (wget error: $errorcode)"
	exit
fi

cd /tmp

tar -xzf nagioscore.tar.gz >/dev/null 2>&1
errorcode=$?
if [ $errorcode != 0 ]; then
        echo -e "${ERROR}ERROR${NC}: An error occured while trying to extract the file (tar error: $errorcode)"
        exit
fi

cd /tmp/nagioscore-nagios-4.3.4/
sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
sudo make all

sudo useradd nagios
sudo usermod -a -G nagios www-data
sudo make install
sudo make install-init
sudo update-rc.d nagios defaults
sudo make install-commandmode
sudo make install-config
sudo make install-webconf
sudo a2enmod rewrite
sudo a2enmod cgi
sudo htpasswd -c -b /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin
sudo systemctl restart apache2
sudo systemctl start nagios

echo -e "${INFO}INFO${NC}: Finished installing nagios"
echo -e "${INFO}INFO${NC}: Installing Nagios Plugins prerequisites"

sudo apt-get install -y -q autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext
wget --no-check-certificate -O /tmp/nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz
cd /tmp
tar zxf nagios-plugins.tar.gz
cd /tmp/nagios-plugins-release-2.2.1/
sudo ./tools/setup
sudo ./configure
sudo make
sudo make install
sudo systemctl restart nagios

cd /tmp
wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz 
tar zxf nrpe-*
cd /tmp/nrpe-*
sudo ./configure
sudo make check_nrpe
sudo make install-plugin
sudo sed -i -e 's+#cfg_dir=/usr/local/nagios/etc/servers+cfg_dir=/usr/local/nagios/etc/servers+g' /usr/local/nagios/etc/nagios.cfg

sudo echo "Define command{" >> /usr/local/nagios/etc/objects/commands.cfg
sudo echo "	command_name check_nrpe" >> /usr/local/nagios/etc/objects/commands.cfg
sudo echo "	command_line $USER1/check_nrpe -H $HOSTADDRESS$ -c $ARG1$" >> /usr/local/nagios/etc/objects/commands.cfg
sudo echo "}" >> /usr/local/nagios/etc/objects/commands.cfg
